### ISSUE TITLE
Checkbox on consent boolean/array

### ISSUE THREAD

**Issue by websmyth** [silentzco/statamic-mailchimp#49]
Not sure if this is an add-on issue, apologies if not...

I’m using a checkbox field as a `consent` and submitting the form with this `checked` returns:

`Return value of Silentz\Mailchimp\Subscriber::hasConsent() must be of the type bool, array returned`

The relevant part of the `blueprint`:

```
-
        handle: mailing_list
        field:
          inline: false
          options:
            'true': 'Subscribe me to the mailing list'
          display: 'Mailing List'
          type: checkboxes
          icon: checkboxes
          listable: hidden
```

Can anything be done to recognise this field/array? I’d guess a `radio` would work, but would prefer for users to be able to check/uncheck.

Perhaps I need to set this up a different way?
