### ISSUE TITLE
Email submissions aren't getting sent the double confirmation email from MC

### ISSUE THREAD

**Issue by austriker27** [silentzco/statamic-mailchimp#65]
Alrighty, I've double checked everything and can't figure out why MC is *not* sending double confirm emails for submissions (I have this turned on per MC recommendation and have checked my spam folder). The submissions are being saved in Statamic and I'm not getting any console errors. Yet no confirmation emails nor new audience contacts. 

Also I added the pages that use the MC signup form to be excluded from caching. 

I only want to save form submissions to MC, not users. 

I reckon something is wrong in my setup and would love your expert eyes. Thanks! 

# SETUP FILES
`mailchimp.php`: (includes my MC API KEY in real life)

```php
<?php

return [

    'api_key' => env('MAILCHIMP_APIKEY'),

    users' => false,

    'users' => [
        'audience_id' => '',

        'disable_opt_in' => false,

        'check_consent' => true,

        'consent_field' => 'consent',

        'merge_fields' => [
            [
                'tag'=> '',

                'field_name' => '',
            ],
        ],

        'disable_opt_in' => false,
    ],

    'forms' => [
        [
            'audience_id' => '0c86e539bc',

            'disable_opt_in' => false,

            'check_consent' => true,

            'consent_field' => 'consent',

            'form' => 'Newsletter',

            'merge_fields' => [
                [
                    'tag'=> 'EMAIL',

                    'field_name' => 'email',
                ],
                [
                    'tag'=> 'SIGNUP',

                    'field_name' => 'merge_field',
                ],
            ],

            'disable_opt_in' => false,
        ],
    ],
];

```

## Newsletter template
`_newsletter_signup.antlers.html` (The partial that includes the newsletter form)
```html
{{ form:newsletter class="w-full" }}
  <div class="lg:flex-row lg:flex lg:items-center lg:justify-between flex flex-col">

    <input type="text" name="honeypot" class="hidden" />

    <div class="w-full space-y-2">
      {{ if success }}
        <p class="sm:text-base sm:leading-6 text-brand-green font-body w-full p-1 italic font-semibold">
          {{ newsletter_signup:confirmation_text }}
        </p>
      {{ else }}
        {{ fields }}
          <div class="lg:flex-row flex">
            <label class="sr-only" for="{{ display }}">{{ display }}</label>
          
            {{ if field:input_type == 'email' }}
              {{ field }}
              <button 
                class="btn rounded-l-none"
                type="submit">
                Sign up
              </button>
            {{ elseif field:handle == 'merge_field' }}
              <input class="hidden"
                      type="text"
                      name="{{ field:handle }}"
                      value="{{ newsletter_signup:merge_field }}" />
            {{ else }}
              <div class="text-xs">
                {{ field }}
              </div>
            {{ /if }}
          </div>
        {{ /fields }}
      {{ /if }}
    </div>

    <div class="lg:mt-0 sm:w-auto lg:ml-4 inline-flex leading-4">
      {{ if success }}
        <button class="btn border-brand-green bg-brand-green btn--xs" type="submit" disabled="">
          <svg class="text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd"
              d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
              clip-rule="evenodd" />
          </svg>
          submitted
        </button>
      {{ elseif errors }}
        <div class="text-brand-pink p-2 font-semibold">
          {{ errors }}
            {{ value }}<br>
          {{ /errors }}
        </div>
        
      {{ /if }}
    </div>

  </div>

  {{ /form:newsletter }}
```

## newsletter blueprint
`resources/blueprints/forms/newsletter.yaml`

```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: email
        field:
          placeholder: name@website.com
          input_type: email
          display: Email
          type: text
          icon: text
          listable: hidden
          validate:
            - required
            - email
          antlers: false
      -
        handle: consent
        field:
          inline: false
          display: Consent
          type: checkboxes
          icon: checkboxes
          listable: hidden
          options:
            'Yes': 'I agree to receive promotional emails and understand I can unsubscribe at any time.'
          validate:
            - required
      -
        handle: merge_field
        field:
          input_type: text
          antlers: false
          display: 'Merge Field'
          type: text
          icon: text
          listable: hidden
          instructions: 'This is a hidden field and edited via the Globals > Newsletter Signup'
```

## Globals > newsletter
`content > globals > newsletter_signup.yaml`

```yaml
title: 'Newsletter Signup'
data:
  header: 'Subscribe to the Workify blog'
  body_text: 'Get our latest insights on building a sustainable business as they''re released.'
  confirmation_text: 'Hurray! Check your email to confirm'
  merge_field: BlogSubscribe
```

# Example Form Submission:
I know the merge tags are getting set correctly because here's a statamic form example YAML file:
(Also I tested to make sure the below email address would receive mail and it can)
```yaml
email: david+test3@zaengle.com
consent:
  - 'Yes'
merge_field: BlogSubscribe
```

# MC settings
- I can confirm "Enable double opt in" is enabled on the MC site 
- I've double checked the audience ID and merge tags. 
- I've double checked the API key Im using in my `.env` is correct and enabled

# Versions
Statamic 3.1.24
Mailchimp 2.5.6
PHP 7.4
